import { ProcessoOperacional, ProcessoHistorico, ProcessoDocumento } from '@/types'

export const mockProcessos: ProcessoOperacional[] = [
  {
    id: 'p1',
    numero_controle: 'PRC-2023-001',
    status: 'em_execucao',
    cia: 'Seguradora Alfa',
    tipo_servico: 'Vistoria Prévia',
    local_sinistro: 'São Paulo - SP',
    agente_prestador: 'João Silva',
    data_entrada: '2023-10-01',
    dias_uteis: 3,
    data_retorno: '2023-10-05',
    data_saida: '',
    resultado: 'analise',
    dias_totais: 4,
    controle_cia: 'ALFA-992',
    nome_segurado: 'Carlos Oliveira',
    placas_veiculos: 'ABC-1234',
    analista_solicitante: 'Maria Souza',
    revisor: 'Pedro Costa',
    observacoes: 'Aguardando envio de documentação complementar pelo segurado.',
    posicao_1: 'Contato realizado com sucesso em 02/10.',
    posicao_2: '',
    posicao_3: '',
    user_id: 'u1',
    created: '2023-10-01T10:00:00.000Z',
    updated: '2023-10-02T15:30:00.000Z',
  },
  {
    id: 'p2',
    numero_controle: 'PRC-2023-002',
    status: 'finalizado',
    cia: 'Seguradora Beta',
    tipo_servico: 'Sindicância',
    local_sinistro: 'Rio de Janeiro - RJ',
    agente_prestador: 'Ana Santos',
    data_entrada: '2023-09-25',
    dias_uteis: 7,
    data_retorno: '2023-10-02',
    data_saida: '2023-10-04',
    resultado: 'regular',
    dias_totais: 9,
    controle_cia: 'BETA-445',
    nome_segurado: 'Fernanda Lima',
    placas_veiculos: 'XYZ-9876',
    analista_solicitante: 'Maria Souza',
    revisor: 'Roberto Almeida',
    observacoes: 'Processo concluído sem ressalvas.',
    posicao_1: 'Visita ao local em 26/09.',
    posicao_2: 'Entrevista com vizinhos em 28/09.',
    posicao_3: 'Relatório entregue em 02/10.',
    user_id: 'u2',
    created: '2023-09-25T09:00:00.000Z',
    updated: '2023-10-04T18:00:00.000Z',
  },
  {
    id: 'p3',
    numero_controle: 'PRC-2023-003',
    status: 'em_elaboracao',
    cia: 'Seguradora Alfa',
    tipo_servico: 'Regulação',
    local_sinistro: 'Campinas - SP',
    agente_prestador: 'Lucas Mendes',
    data_entrada: '2023-10-10',
    dias_uteis: 1,
    data_retorno: '',
    data_saida: '',
    resultado: '',
    dias_totais: 1,
    controle_cia: 'ALFA-1002',
    nome_segurado: 'Empresa XYZ',
    placas_veiculos: 'DEF-5555',
    analista_solicitante: 'Ricardo Nunes',
    revisor: '',
    observacoes: '',
    posicao_1: '',
    posicao_2: '',
    posicao_3: '',
    user_id: 'u1',
    created: '2023-10-10T11:20:00.000Z',
    updated: '2023-10-10T11:20:00.000Z',
  },
]

export const mockHistorico: ProcessoHistorico[] = [
  {
    id: 'h1',
    processo_id: 'p1',
    tipo_evento: 'criado',
    descricao: 'Processo criado no sistema.',
    user_name: 'Maria Souza',
    created: '2023-10-01T10:00:00.000Z',
  },
  {
    id: 'h2',
    processo_id: 'p1',
    tipo_evento: 'status_alterado',
    descricao: 'Status alterado para Em Execução.',
    user_name: 'Maria Souza',
    data_anteriores: 'em_elaboracao',
    data_novos: 'em_execucao',
    created: '2023-10-02T15:30:00.000Z',
  },
]

export const mockDocumentos: ProcessoDocumento[] = [
  {
    id: 'd1',
    processo_id: 'p1',
    arquivo: 'doc_123.pdf',
    name: 'Boletim_Ocorrencia.pdf',
    size: 1024500,
    created: '2023-10-02T14:00:00.000Z',
    url: '#',
  },
]
