import { Prestador } from '@/types'

export const mockPrestadores: Prestador[] = [
  {
    id: '1',
    nomeCompleto: 'João Silva Santos',
    dataNascimento: '1990-05-15',
    cpf: '111.222.333-44',
    rg: '12.345.678-9',
    cnpj: '12.345.678/0001-90',
    possuiCnpj: 'Sim',
    emiteNotaFiscal: 'Sim',
    notaTerceiros: 'Não',
    baseAtendimento: 'São Paulo Centro',
    regiaoAbrangencia: 'SP Capital',
    cepBase: '01000-000',
    telefone: '(11) 98888-7777',
    email: 'joao.santos@email.com',
    banco: 'Itaú',
    agencia: '1234',
    conta: '56789-0',
    titularConta: 'João Silva Santos',
    chavePix: '111.222.333-44',
    dadosBancariosTerceiros: 'Não',
    valorHonorario: 150.0,
    valorKm: 1.5,
    ativo: 'Sim',
    dataAtivacao: '2023-01-10',
    naBlackList: 'Não',
    outrasEmpresas: 'Empresa A, Empresa B',
    origemIndicacao: 'LinkedIn',
    observacoes: 'Excelente profissional.',
  },
  {
    id: '2',
    nomeCompleto: 'Maria Oliveira',
    dataNascimento: '1985-10-20',
    cpf: '555.666.777-88',
    rg: '98.765.432-1',
    cnpj: '',
    possuiCnpj: 'Não',
    emiteNotaFiscal: 'Não',
    notaTerceiros: 'Sim',
    vinculoTerceiroNf: 'Cônjuge',
    baseAtendimento: 'Rio de Janeiro Sul',
    regiaoAbrangencia: 'RJ Sul',
    cepBase: '22000-000',
    telefone: '(21) 97777-6666',
    email: 'maria.oliveira@email.com',
    banco: 'Bradesco',
    agencia: '4321',
    conta: '09876-5',
    titularConta: 'Carlos Oliveira (Marido)',
    chavePix: 'carlos@email.com',
    dadosBancariosTerceiros: 'Sim',
    vinculoTerceiroBanco: 'Cônjuge',
    valorHonorario: 180.0,
    valorKm: 2.0,
    ativo: 'Não',
    dataAtivacao: '2022-05-01',
    dataInativacao: '2024-02-15',
    naBlackList: 'Sim',
    motivoBlackList: 'Atrasos frequentes.',
    outrasEmpresas: 'Nenhuma',
    origemIndicacao: 'Indicação interna',
    observacoes: 'Monitorar caso retorne.',
  },
]
