migrate(
  (app) => {
    // Seed auth user
    const users = app.findCollectionByNameOrId('_pb_users_auth_')
    const user = new Record(users)
    user.setEmail('valmor.junior@inquiry.com.br')
    user.setPassword('securepassword123')
    user.setVerified(true)
    app.save(user)

    // Seed prestadores
    const prestadores = app.findCollectionByNameOrId('prestadores')

    const p1 = new Record(prestadores)
    p1.set('nomeCompleto', 'João Silva Santos')
    p1.set('dataNascimento', '1990-05-15')
    p1.set('cpf', '111.222.333-44')
    p1.set('rg', '12.345.678-9')
    p1.set('cnpj', '12.345.678/0001-90')
    p1.set('possuiCnpj', 'Sim')
    p1.set('emiteNotaFiscal', 'Sim')
    p1.set('notaTerceiros', 'Não')
    p1.set('baseAtendimento', 'São Paulo Centro')
    p1.set('regiaoAbrangencia', 'SP Capital')
    p1.set('cepBase', '01000-000')
    p1.set('telefone', '(11) 98888-7777')
    p1.set('email', 'joao.santos@email.com')
    p1.set('banco', 'Itaú')
    p1.set('agencia', '1234')
    p1.set('conta', '56789-0')
    p1.set('titularConta', 'João Silva Santos')
    p1.set('chavePix', '111.222.333-44')
    p1.set('dadosBancariosTerceiros', 'Não')
    p1.set('valorHonorario', 150.0)
    p1.set('valorKm', 1.5)
    p1.set('ativo', 'Sim')
    p1.set('dataAtivacao', '2023-01-10')
    p1.set('naBlackList', 'Não')
    p1.set('outrasEmpresas', 'Empresa A, Empresa B')
    p1.set('origemIndicacao', 'LinkedIn')
    p1.set('observacoes', 'Excelente profissional.')
    app.save(p1)

    const p2 = new Record(prestadores)
    p2.set('nomeCompleto', 'Maria Oliveira')
    p2.set('dataNascimento', '1985-10-20')
    p2.set('cpf', '555.666.777-88')
    p2.set('rg', '98.765.432-1')
    p2.set('possuiCnpj', 'Não')
    p2.set('emiteNotaFiscal', 'Não')
    p2.set('notaTerceiros', 'Sim')
    p2.set('vinculoTerceiroNf', 'Cônjuge')
    p2.set('baseAtendimento', 'Rio de Janeiro Sul')
    p2.set('regiaoAbrangencia', 'RJ Sul')
    p2.set('cepBase', '22000-000')
    p2.set('telefone', '(21) 97777-6666')
    p2.set('email', 'maria.oliveira@email.com')
    p2.set('banco', 'Bradesco')
    p2.set('agencia', '4321')
    p2.set('conta', '09876-5')
    p2.set('titularConta', 'Carlos Oliveira (Marido)')
    p2.set('chavePix', 'carlos@email.com')
    p2.set('dadosBancariosTerceiros', 'Sim')
    p2.set('vinculoTerceiroBanco', 'Cônjuge')
    p2.set('valorHonorario', 180.0)
    p2.set('valorKm', 2.0)
    p2.set('ativo', 'Não')
    p2.set('dataAtivacao', '2022-05-01')
    p2.set('dataInativacao', '2024-02-15')
    p2.set('naBlackList', 'Sim')
    p2.set('motivoBlackList', 'Atrasos frequentes.')
    p2.set('outrasEmpresas', 'Nenhuma')
    p2.set('origemIndicacao', 'Indicação interna')
    p2.set('observacoes', 'Monitorar caso retorne.')
    app.save(p2)
  },
  (app) => {
    try {
      const user = app.findAuthRecordByEmail('_pb_users_auth_', 'valmor.junior@inquiry.com.br')
      app.delete(user)
    } catch (_) {}
    const prestadores = app.findCollectionByNameOrId('prestadores')
    app.truncateCollection(prestadores)
  },
)
