migrate(
  (app) => {
    const colProcessos = app.findCollectionByNameOrId('processos_operacionais')
    const colHistorico = app.findCollectionByNameOrId('processos_historico')

    const p1 = new Record(colProcessos)
    p1.set('numero_controle', 'PRC-2023-001')
    p1.set('status', 'em_execucao')
    p1.set('cia', 'Seguradora Alfa')
    p1.set('tipo_servico', 'Vistoria Prévia')
    p1.set('local_sinistro', 'São Paulo - SP')
    p1.set('agente_prestador', 'João Silva')
    p1.set('data_entrada', '2023-10-01')
    p1.set('dias_uteis', 3)
    p1.set('data_retorno', '2023-10-05')
    p1.set('data_saida', '')
    p1.set('resultado', 'analise')
    p1.set('dias_totais', 4)
    p1.set('controle_cia', 'ALFA-992')
    p1.set('nome_segurado', 'Carlos Oliveira')
    p1.set('placas_veiculos', 'ABC-1234')
    p1.set('analista_solicitante', 'Maria Souza')
    p1.set('revisor', 'Pedro Costa')
    p1.set('observacoes', 'Aguardando envio de documentação complementar pelo segurado.')
    p1.set('posicao_1', 'Contato realizado com sucesso em 02/10.')
    p1.set('posicao_2', '')
    p1.set('posicao_3', '')
    p1.set('user_id', 'u1')
    app.save(p1)

    const h1 = new Record(colHistorico)
    h1.set('processo_id', p1.id)
    h1.set('tipo_evento', 'criado')
    h1.set('descricao', 'Processo criado no sistema.')
    h1.set('user_name', 'Maria Souza')
    app.save(h1)

    const h2 = new Record(colHistorico)
    h2.set('processo_id', p1.id)
    h2.set('tipo_evento', 'status_alterado')
    h2.set('descricao', 'Status alterado para Em Execução.')
    h2.set('user_name', 'Maria Souza')
    h2.set('data_anteriores', 'em_elaboracao')
    h2.set('data_novos', 'em_execucao')
    app.save(h2)

    const p2 = new Record(colProcessos)
    p2.set('numero_controle', 'PRC-2023-002')
    p2.set('status', 'finalizado')
    p2.set('cia', 'Seguradora Beta')
    p2.set('tipo_servico', 'Sindicância')
    p2.set('local_sinistro', 'Rio de Janeiro - RJ')
    p2.set('agente_prestador', 'Ana Santos')
    p2.set('data_entrada', '2023-09-25')
    p2.set('dias_uteis', 7)
    p2.set('data_retorno', '2023-10-02')
    p2.set('data_saida', '2023-10-04')
    p2.set('resultado', 'regular')
    p2.set('dias_totais', 9)
    p2.set('controle_cia', 'BETA-445')
    p2.set('nome_segurado', 'Fernanda Lima')
    p2.set('placas_veiculos', 'XYZ-9876')
    p2.set('analista_solicitante', 'Maria Souza')
    p2.set('revisor', 'Roberto Almeida')
    p2.set('observacoes', 'Processo concluído sem ressalvas.')
    p2.set('posicao_1', 'Visita ao local em 26/09.')
    p2.set('posicao_2', 'Entrevista com vizinhos em 28/09.')
    p2.set('posicao_3', 'Relatório entregue em 02/10.')
    p2.set('user_id', 'u2')
    app.save(p2)

    const p3 = new Record(colProcessos)
    p3.set('numero_controle', 'PRC-2023-003')
    p3.set('status', 'em_elaboracao')
    p3.set('cia', 'Seguradora Alfa')
    p3.set('tipo_servico', 'Regulação')
    p3.set('local_sinistro', 'Campinas - SP')
    p3.set('agente_prestador', 'Lucas Mendes')
    p3.set('data_entrada', '2023-10-10')
    p3.set('dias_uteis', 1)
    p3.set('data_retorno', '')
    p3.set('data_saida', '')
    p3.set('resultado', '')
    p3.set('dias_totais', 1)
    p3.set('controle_cia', 'ALFA-1002')
    p3.set('nome_segurado', 'Empresa XYZ')
    p3.set('placas_veiculos', 'DEF-5555')
    p3.set('analista_solicitante', 'Ricardo Nunes')
    p3.set('revisor', '')
    p3.set('observacoes', '')
    p3.set('posicao_1', '')
    p3.set('posicao_2', '')
    p3.set('posicao_3', '')
    p3.set('user_id', 'u1')
    app.save(p3)
  },
  (app) => {
    const records = app.findRecordsByFilter(
      'processos_operacionais',
      "numero_controle ~ 'PRC-2023-'",
      '',
      10,
      0,
    )
    for (const r of records) {
      app.delete(r)
    }
  },
)
